pub use orion_pool_v2erc20::*;
#[allow(
    clippy::too_many_arguments,
    non_camel_case_types,
    clippy::upper_case_acronyms
)]
pub mod orion_pool_v2erc20 {
    #![allow(clippy::enum_variant_names)]
    #![allow(dead_code)]
    #![allow(clippy::type_complexity)]
    #![allow(unused_imports)]
    //!OrionPoolV2ERC20 was auto-generated with ethers-rs Abigen. More information at: <https://github.com/gakonst/ethers-rs>
    use ::ethers::contract::{
        builders::{ContractCall, Event},
        Contract, Lazy,
    };
    use ::ethers::core::{
        abi::{Abi, Detokenize, InvalidOutputType, Token, Tokenizable},
        types::*,
    };
    use ::ethers::providers::Middleware;
    use std::sync::Arc;
    #[rustfmt::skip]
    const __ABI: &str = "[{\"inputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"constructor\",\"outputs\":[]},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"owner\",\"type\":\"address\",\"components\":[],\"indexed\":true},{\"internalType\":\"address\",\"name\":\"spender\",\"type\":\"address\",\"components\":[],\"indexed\":true},{\"internalType\":\"uint256\",\"name\":\"value\",\"type\":\"uint256\",\"components\":[],\"indexed\":false}],\"type\":\"event\",\"name\":\"Approval\",\"outputs\":[],\"anonymous\":false},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"from\",\"type\":\"address\",\"components\":[],\"indexed\":true},{\"internalType\":\"address\",\"name\":\"to\",\"type\":\"address\",\"components\":[],\"indexed\":true},{\"internalType\":\"uint256\",\"name\":\"value\",\"type\":\"uint256\",\"components\":[],\"indexed\":false}],\"type\":\"event\",\"name\":\"Transfer\",\"outputs\":[],\"anonymous\":false},{\"inputs\":[],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"DOMAIN_SEPARATOR\",\"outputs\":[{\"internalType\":\"bytes32\",\"name\":\"\",\"type\":\"bytes32\",\"components\":[]}]},{\"inputs\":[],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"PERMIT_TYPEHASH\",\"outputs\":[{\"internalType\":\"bytes32\",\"name\":\"\",\"type\":\"bytes32\",\"components\":[]}]},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\",\"components\":[]},{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\",\"components\":[]}],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"allowance\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\",\"components\":[]}]},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"spender\",\"type\":\"address\",\"components\":[]},{\"internalType\":\"uint256\",\"name\":\"value\",\"type\":\"uint256\",\"components\":[]}],\"stateMutability\":\"nonpayable\",\"type\":\"function\",\"name\":\"approve\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"\",\"type\":\"bool\",\"components\":[]}]},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\",\"components\":[]}],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"balanceOf\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\",\"components\":[]}]},{\"inputs\":[],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"decimals\",\"outputs\":[{\"internalType\":\"uint8\",\"name\":\"\",\"type\":\"uint8\",\"components\":[]}]},{\"inputs\":[],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"name\",\"outputs\":[{\"internalType\":\"string\",\"name\":\"\",\"type\":\"string\",\"components\":[]}]},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\",\"components\":[]}],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"nonces\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\",\"components\":[]}]},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"owner\",\"type\":\"address\",\"components\":[]},{\"internalType\":\"address\",\"name\":\"spender\",\"type\":\"address\",\"components\":[]},{\"internalType\":\"uint256\",\"name\":\"value\",\"type\":\"uint256\",\"components\":[]},{\"internalType\":\"uint256\",\"name\":\"deadline\",\"type\":\"uint256\",\"components\":[]},{\"internalType\":\"uint8\",\"name\":\"v\",\"type\":\"uint8\",\"components\":[]},{\"internalType\":\"bytes32\",\"name\":\"r\",\"type\":\"bytes32\",\"components\":[]},{\"internalType\":\"bytes32\",\"name\":\"s\",\"type\":\"bytes32\",\"components\":[]}],\"stateMutability\":\"nonpayable\",\"type\":\"function\",\"name\":\"permit\",\"outputs\":[]},{\"inputs\":[],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"symbol\",\"outputs\":[{\"internalType\":\"string\",\"name\":\"\",\"type\":\"string\",\"components\":[]}]},{\"inputs\":[],\"stateMutability\":\"view\",\"type\":\"function\",\"name\":\"totalSupply\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\",\"components\":[]}]},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"to\",\"type\":\"address\",\"components\":[]},{\"internalType\":\"uint256\",\"name\":\"value\",\"type\":\"uint256\",\"components\":[]}],\"stateMutability\":\"nonpayable\",\"type\":\"function\",\"name\":\"transfer\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"\",\"type\":\"bool\",\"components\":[]}]},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"from\",\"type\":\"address\",\"components\":[]},{\"internalType\":\"address\",\"name\":\"to\",\"type\":\"address\",\"components\":[]},{\"internalType\":\"uint256\",\"name\":\"value\",\"type\":\"uint256\",\"components\":[]}],\"stateMutability\":\"nonpayable\",\"type\":\"function\",\"name\":\"transferFrom\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"\",\"type\":\"bool\",\"components\":[]}]}]";
    ///The parsed JSON ABI of the contract.
    pub static ORIONPOOLV2ERC20_ABI: ::ethers::contract::Lazy<::ethers::core::abi::Abi> =
        ::ethers::contract::Lazy::new(|| {
            ::ethers::core::utils::__serde_json::from_str(__ABI).expect("ABI is always valid")
        });
    #[rustfmt::skip]
    const __BYTECODE: &[u8] = &[
        96,
        128,
        96,
        64,
        82,
        52,
        128,
        21,
        97,
        0,
        16,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        96,
        64,
        128,
        81,
        128,
        130,
        1,
        130,
        82,
        96,
        12,
        129,
        82,
        107,
        39,
        185,
        52,
        183,
        183,
        40,
        55,
        183,
        182,
        16,
        43,
        25,
        96,
        161,
        27,
        96,
        32,
        145,
        130,
        1,
        82,
        129,
        81,
        128,
        131,
        1,
        131,
        82,
        96,
        1,
        129,
        82,
        96,
        49,
        96,
        248,
        27,
        144,
        130,
        1,
        82,
        129,
        81,
        127,
        139,
        115,
        195,
        198,
        155,
        184,
        254,
        61,
        81,
        46,
        204,
        76,
        247,
        89,
        204,
        121,
        35,
        159,
        123,
        23,
        155,
        15,
        250,
        202,
        169,
        167,
        93,
        82,
        43,
        57,
        64,
        15,
        129,
        131,
        1,
        82,
        127,
        188,
        37,
        28,
        34,
        163,
        210,
        216,
        220,
        68,
        236,
        104,
        90,
        84,
        227,
        189,
        26,
        150,
        129,
        156,
        183,
        244,
        37,
        230,
        150,
        104,
        163,
        185,
        134,
        160,
        40,
        220,
        175,
        129,
        132,
        1,
        82,
        127,
        200,
        158,
        253,
        170,
        84,
        192,
        242,
        12,
        122,
        223,
        97,
        40,
        130,
        223,
        9,
        80,
        245,
        169,
        81,
        99,
        126,
        3,
        7,
        205,
        203,
        76,
        103,
        47,
        41,
        139,
        139,
        198,
        96,
        96,
        130,
        1,
        82,
        70,
        96,
        128,
        130,
        1,
        82,
        48,
        96,
        160,
        128,
        131,
        1,
        145,
        144,
        145,
        82,
        131,
        81,
        128,
        131,
        3,
        144,
        145,
        1,
        129,
        82,
        96,
        192,
        144,
        145,
        1,
        144,
        146,
        82,
        129,
        81,
        145,
        1,
        32,
        96,
        3,
        85,
        97,
        8,
        122,
        128,
        97,
        0,
        243,
        96,
        0,
        57,
        96,
        0,
        243,
        254,
        96,
        128,
        96,
        64,
        82,
        52,
        128,
        21,
        97,
        0,
        16,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        96,
        4,
        54,
        16,
        97,
        0,
        207,
        87,
        96,
        0,
        53,
        96,
        224,
        28,
        128,
        99,
        54,
        68,
        229,
        21,
        17,
        97,
        0,
        140,
        87,
        128,
        99,
        149,
        216,
        155,
        65,
        17,
        97,
        0,
        102,
        87,
        128,
        99,
        149,
        216,
        155,
        65,
        20,
        97,
        1,
        236,
        87,
        128,
        99,
        169,
        5,
        156,
        187,
        20,
        97,
        2,
        17,
        87,
        128,
        99,
        213,
        5,
        172,
        207,
        20,
        97,
        2,
        36,
        87,
        128,
        99,
        221,
        98,
        237,
        62,
        20,
        97,
        2,
        57,
        87,
        96,
        0,
        128,
        253,
        91,
        128,
        99,
        54,
        68,
        229,
        21,
        20,
        97,
        1,
        163,
        87,
        128,
        99,
        112,
        160,
        130,
        49,
        20,
        97,
        1,
        172,
        87,
        128,
        99,
        126,
        206,
        190,
        0,
        20,
        97,
        1,
        204,
        87,
        96,
        0,
        128,
        253,
        91,
        128,
        99,
        6,
        253,
        222,
        3,
        20,
        97,
        0,
        212,
        87,
        128,
        99,
        9,
        94,
        167,
        179,
        20,
        97,
        1,
        21,
        87,
        128,
        99,
        24,
        22,
        13,
        221,
        20,
        97,
        1,
        56,
        87,
        128,
        99,
        35,
        184,
        114,
        221,
        20,
        97,
        1,
        79,
        87,
        128,
        99,
        48,
        173,
        248,
        31,
        20,
        97,
        1,
        98,
        87,
        128,
        99,
        49,
        60,
        229,
        103,
        20,
        97,
        1,
        137,
        87,
        91,
        96,
        0,
        128,
        253,
        91,
        97,
        0,
        255,
        96,
        64,
        81,
        128,
        96,
        64,
        1,
        96,
        64,
        82,
        128,
        96,
        12,
        129,
        82,
        96,
        32,
        1,
        107,
        39,
        185,
        52,
        183,
        183,
        40,
        55,
        183,
        182,
        16,
        43,
        25,
        96,
        161,
        27,
        129,
        82,
        80,
        129,
        86,
        91,
        96,
        64,
        81,
        97,
        1,
        12,
        145,
        144,
        97,
        6,
        94,
        86,
        91,
        96,
        64,
        81,
        128,
        145,
        3,
        144,
        243,
        91,
        97,
        1,
        40,
        97,
        1,
        35,
        54,
        96,
        4,
        97,
        6,
        200,
        86,
        91,
        97,
        2,
        100,
        86,
        91,
        96,
        64,
        81,
        144,
        21,
        21,
        129,
        82,
        96,
        32,
        1,
        97,
        1,
        12,
        86,
        91,
        97,
        1,
        65,
        96,
        0,
        84,
        129,
        86,
        91,
        96,
        64,
        81,
        144,
        129,
        82,
        96,
        32,
        1,
        97,
        1,
        12,
        86,
        91,
        97,
        1,
        40,
        97,
        1,
        93,
        54,
        96,
        4,
        97,
        6,
        242,
        86,
        91,
        97,
        2,
        123,
        86,
        91,
        97,
        1,
        65,
        127,
        110,
        113,
        237,
        174,
        18,
        177,
        185,
        127,
        77,
        31,
        96,
        55,
        15,
        239,
        16,
        16,
        95,
        162,
        250,
        174,
        1,
        38,
        17,
        74,
        22,
        156,
        100,
        132,
        93,
        97,
        38,
        201,
        129,
        86,
        91,
        97,
        1,
        145,
        96,
        18,
        129,
        86,
        91,
        96,
        64,
        81,
        96,
        255,
        144,
        145,
        22,
        129,
        82,
        96,
        32,
        1,
        97,
        1,
        12,
        86,
        91,
        97,
        1,
        65,
        96,
        3,
        84,
        129,
        86,
        91,
        97,
        1,
        65,
        97,
        1,
        186,
        54,
        96,
        4,
        97,
        7,
        46,
        86,
        91,
        96,
        1,
        96,
        32,
        82,
        96,
        0,
        144,
        129,
        82,
        96,
        64,
        144,
        32,
        84,
        129,
        86,
        91,
        97,
        1,
        65,
        97,
        1,
        218,
        54,
        96,
        4,
        97,
        7,
        46,
        86,
        91,
        96,
        4,
        96,
        32,
        82,
        96,
        0,
        144,
        129,
        82,
        96,
        64,
        144,
        32,
        84,
        129,
        86,
        91,
        97,
        0,
        255,
        96,
        64,
        81,
        128,
        96,
        64,
        1,
        96,
        64,
        82,
        128,
        96,
        6,
        129,
        82,
        96,
        32,
        1,
        101,
        42,
        167,
        36,
        150,
        171,
        25,
        96,
        209,
        27,
        129,
        82,
        80,
        129,
        86,
        91,
        97,
        1,
        40,
        97,
        2,
        31,
        54,
        96,
        4,
        97,
        6,
        200,
        86,
        91,
        97,
        3,
        15,
        86,
        91,
        97,
        2,
        55,
        97,
        2,
        50,
        54,
        96,
        4,
        97,
        7,
        73,
        86,
        91,
        97,
        3,
        28,
        86,
        91,
        0,
        91,
        97,
        1,
        65,
        97,
        2,
        71,
        54,
        96,
        4,
        97,
        7,
        188,
        86,
        91,
        96,
        2,
        96,
        32,
        144,
        129,
        82,
        96,
        0,
        146,
        131,
        82,
        96,
        64,
        128,
        132,
        32,
        144,
        145,
        82,
        144,
        130,
        82,
        144,
        32,
        84,
        129,
        86,
        91,
        96,
        0,
        97,
        2,
        113,
        51,
        132,
        132,
        97,
        5,
        55,
        86,
        91,
        80,
        96,
        1,
        91,
        146,
        145,
        80,
        80,
        86,
        91,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        131,
        22,
        96,
        0,
        144,
        129,
        82,
        96,
        2,
        96,
        32,
        144,
        129,
        82,
        96,
        64,
        128,
        131,
        32,
        51,
        132,
        82,
        144,
        145,
        82,
        129,
        32,
        84,
        96,
        0,
        25,
        20,
        97,
        2,
        250,
        87,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        132,
        22,
        96,
        0,
        144,
        129,
        82,
        96,
        2,
        96,
        32,
        144,
        129,
        82,
        96,
        64,
        128,
        131,
        32,
        51,
        132,
        82,
        144,
        145,
        82,
        144,
        32,
        84,
        97,
        2,
        213,
        144,
        131,
        97,
        5,
        153,
        86,
        91,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        133,
        22,
        96,
        0,
        144,
        129,
        82,
        96,
        2,
        96,
        32,
        144,
        129,
        82,
        96,
        64,
        128,
        131,
        32,
        51,
        132,
        82,
        144,
        145,
        82,
        144,
        32,
        85,
        91,
        97,
        3,
        5,
        132,
        132,
        132,
        97,
        5,
        172,
        86,
        91,
        80,
        96,
        1,
        147,
        146,
        80,
        80,
        80,
        86,
        91,
        96,
        0,
        97,
        2,
        113,
        51,
        132,
        132,
        97,
        5,
        172,
        86,
        91,
        66,
        132,
        16,
        21,
        97,
        3,
        104,
        87,
        96,
        64,
        81,
        98,
        70,
        27,
        205,
        96,
        229,
        27,
        129,
        82,
        96,
        32,
        96,
        4,
        130,
        1,
        82,
        96,
        20,
        96,
        36,
        130,
        1,
        82,
        115,
        19,
        220,
        154,
        91,
        219,
        148,
        27,
        219,
        219,
        21,
        140,
        142,
        136,
        17,
        86,
        20,
        18,
        84,
        145,
        81,
        96,
        98,
        27,
        96,
        68,
        130,
        1,
        82,
        96,
        100,
        1,
        91,
        96,
        64,
        81,
        128,
        145,
        3,
        144,
        253,
        91,
        96,
        3,
        84,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        136,
        22,
        96,
        0,
        144,
        129,
        82,
        96,
        4,
        96,
        32,
        82,
        96,
        64,
        129,
        32,
        128,
        84,
        145,
        146,
        145,
        127,
        110,
        113,
        237,
        174,
        18,
        177,
        185,
        127,
        77,
        31,
        96,
        55,
        15,
        239,
        16,
        16,
        95,
        162,
        250,
        174,
        1,
        38,
        17,
        74,
        22,
        156,
        100,
        132,
        93,
        97,
        38,
        201,
        145,
        139,
        145,
        139,
        145,
        139,
        145,
        144,
        135,
        97,
        3,
        187,
        131,
        97,
        8,
        5,
        86,
        91,
        144,
        145,
        85,
        80,
        96,
        64,
        128,
        81,
        96,
        32,
        129,
        1,
        150,
        144,
        150,
        82,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        148,
        133,
        22,
        144,
        134,
        1,
        82,
        146,
        144,
        145,
        22,
        96,
        96,
        132,
        1,
        82,
        96,
        128,
        131,
        1,
        82,
        96,
        160,
        130,
        1,
        82,
        96,
        192,
        129,
        1,
        135,
        144,
        82,
        96,
        224,
        1,
        96,
        64,
        81,
        96,
        32,
        129,
        131,
        3,
        3,
        129,
        82,
        144,
        96,
        64,
        82,
        128,
        81,
        144,
        96,
        32,
        1,
        32,
        96,
        64,
        81,
        96,
        32,
        1,
        97,
        4,
        52,
        146,
        145,
        144,
        97,
        25,
        1,
        96,
        240,
        27,
        129,
        82,
        96,
        2,
        129,
        1,
        146,
        144,
        146,
        82,
        96,
        34,
        130,
        1,
        82,
        96,
        66,
        1,
        144,
        86,
        91,
        96,
        64,
        128,
        81,
        96,
        31,
        25,
        129,
        132,
        3,
        1,
        129,
        82,
        130,
        130,
        82,
        128,
        81,
        96,
        32,
        145,
        130,
        1,
        32,
        96,
        0,
        128,
        133,
        82,
        145,
        132,
        1,
        128,
        132,
        82,
        129,
        144,
        82,
        96,
        255,
        136,
        22,
        146,
        132,
        1,
        146,
        144,
        146,
        82,
        96,
        96,
        131,
        1,
        134,
        144,
        82,
        96,
        128,
        131,
        1,
        133,
        144,
        82,
        144,
        146,
        80,
        144,
        96,
        1,
        144,
        96,
        160,
        1,
        96,
        32,
        96,
        64,
        81,
        96,
        32,
        129,
        3,
        144,
        128,
        132,
        3,
        144,
        133,
        90,
        250,
        21,
        128,
        21,
        97,
        4,
        159,
        87,
        61,
        96,
        0,
        128,
        62,
        61,
        96,
        0,
        253,
        91,
        80,
        80,
        96,
        64,
        81,
        96,
        31,
        25,
        1,
        81,
        145,
        80,
        80,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        129,
        22,
        21,
        128,
        21,
        144,
        97,
        4,
        213,
        87,
        80,
        136,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        22,
        129,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        22,
        20,
        91,
        97,
        5,
        33,
        87,
        96,
        64,
        81,
        98,
        70,
        27,
        205,
        96,
        229,
        27,
        129,
        82,
        96,
        32,
        96,
        4,
        130,
        1,
        82,
        96,
        30,
        96,
        36,
        130,
        1,
        82,
        127,
        79,
        114,
        105,
        111,
        110,
        80,
        111,
        111,
        108,
        86,
        50,
        58,
        32,
        73,
        78,
        86,
        65,
        76,
        73,
        68,
        95,
        83,
        73,
        71,
        78,
        65,
        84,
        85,
        82,
        69,
        0,
        0,
        96,
        68,
        130,
        1,
        82,
        96,
        100,
        1,
        97,
        3,
        95,
        86,
        91,
        97,
        5,
        44,
        137,
        137,
        137,
        97,
        5,
        55,
        86,
        91,
        80,
        80,
        80,
        80,
        80,
        80,
        80,
        80,
        80,
        86,
        91,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        131,
        129,
        22,
        96,
        0,
        129,
        129,
        82,
        96,
        2,
        96,
        32,
        144,
        129,
        82,
        96,
        64,
        128,
        131,
        32,
        148,
        135,
        22,
        128,
        132,
        82,
        148,
        130,
        82,
        145,
        130,
        144,
        32,
        133,
        144,
        85,
        144,
        81,
        132,
        129,
        82,
        127,
        140,
        91,
        225,
        229,
        235,
        236,
        125,
        91,
        209,
        79,
        113,
        66,
        125,
        30,
        132,
        243,
        221,
        3,
        20,
        192,
        247,
        178,
        41,
        30,
        91,
        32,
        10,
        200,
        199,
        195,
        185,
        37,
        145,
        1,
        91,
        96,
        64,
        81,
        128,
        145,
        3,
        144,
        163,
        80,
        80,
        80,
        86,
        91,
        96,
        0,
        97,
        5,
        165,
        130,
        132,
        97,
        8,
        30,
        86,
        91,
        147,
        146,
        80,
        80,
        80,
        86,
        91,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        131,
        22,
        96,
        0,
        144,
        129,
        82,
        96,
        1,
        96,
        32,
        82,
        96,
        64,
        144,
        32,
        84,
        97,
        5,
        207,
        144,
        130,
        97,
        5,
        153,
        86,
        91,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        128,
        133,
        22,
        96,
        0,
        144,
        129,
        82,
        96,
        1,
        96,
        32,
        82,
        96,
        64,
        128,
        130,
        32,
        147,
        144,
        147,
        85,
        144,
        132,
        22,
        129,
        82,
        32,
        84,
        97,
        5,
        254,
        144,
        130,
        97,
        6,
        82,
        86,
        91,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        128,
        132,
        22,
        96,
        0,
        129,
        129,
        82,
        96,
        1,
        96,
        32,
        82,
        96,
        64,
        144,
        129,
        144,
        32,
        147,
        144,
        147,
        85,
        145,
        81,
        144,
        133,
        22,
        144,
        127,
        221,
        242,
        82,
        173,
        27,
        226,
        200,
        155,
        105,
        194,
        176,
        104,
        252,
        55,
        141,
        170,
        149,
        43,
        167,
        241,
        99,
        196,
        161,
        22,
        40,
        245,
        90,
        77,
        245,
        35,
        179,
        239,
        144,
        97,
        5,
        140,
        144,
        133,
        129,
        82,
        96,
        32,
        1,
        144,
        86,
        91,
        96,
        0,
        97,
        5,
        165,
        130,
        132,
        97,
        8,
        49,
        86,
        91,
        96,
        0,
        96,
        32,
        128,
        131,
        82,
        131,
        81,
        128,
        130,
        133,
        1,
        82,
        96,
        0,
        91,
        129,
        129,
        16,
        21,
        97,
        6,
        139,
        87,
        133,
        129,
        1,
        131,
        1,
        81,
        133,
        130,
        1,
        96,
        64,
        1,
        82,
        130,
        1,
        97,
        6,
        111,
        86,
        91,
        80,
        96,
        0,
        96,
        64,
        130,
        134,
        1,
        1,
        82,
        96,
        64,
        96,
        31,
        25,
        96,
        31,
        131,
        1,
        22,
        133,
        1,
        1,
        146,
        80,
        80,
        80,
        146,
        145,
        80,
        80,
        86,
        91,
        128,
        53,
        96,
        1,
        96,
        1,
        96,
        160,
        27,
        3,
        129,
        22,
        129,
        20,
        97,
        6,
        195,
        87,
        96,
        0,
        128,
        253,
        91,
        145,
        144,
        80,
        86,
        91,
        96,
        0,
        128,
        96,
        64,
        131,
        133,
        3,
        18,
        21,
        97,
        6,
        219,
        87,
        96,
        0,
        128,
        253,
        91,
        97,
        6,
        228,
        131,
        97,
        6,
        172,
        86,
        91,
        148,
        96,
        32,
        147,
        144,
        147,
        1,
        53,
        147,
        80,
        80,
        80,
        86,
        91,
        96,
        0,
        128,
        96,
        0,
        96,
        96,
        132,
        134,
        3,
        18,
        21,
        97,
        7,
        7,
        87,
        96,
        0,
        128,
        253,
        91,
        97,
        7,
        16,
        132,
        97,
        6,
        172,
        86,
        91,
        146,
        80,
        97,
        7,
        30,
        96,
        32,
        133,
        1,
        97,
        6,
        172,
        86,
        91,
        145,
        80,
        96,
        64,
        132,
        1,
        53,
        144,
        80,
        146,
        80,
        146,
        80,
        146,
        86,
        91,
        96,
        0,
        96,
        32,
        130,
        132,
        3,
        18,
        21,
        97,
        7,
        64,
        87,
        96,
        0,
        128,
        253,
        91,
        97,
        5,
        165,
        130,
        97,
        6,
        172,
        86,
        91,
        96,
        0,
        128,
        96,
        0,
        128,
        96,
        0,
        128,
        96,
        0,
        96,
        224,
        136,
        138,
        3,
        18,
        21,
        97,
        7,
        100,
        87,
        96,
        0,
        128,
        253,
        91,
        97,
        7,
        109,
        136,
        97,
        6,
        172,
        86,
        91,
        150,
        80,
        97,
        7,
        123,
        96,
        32,
        137,
        1,
        97,
        6,
        172,
        86,
        91,
        149,
        80,
        96,
        64,
        136,
        1,
        53,
        148,
        80,
        96,
        96,
        136,
        1,
        53,
        147,
        80,
        96,
        128,
        136,
        1,
        53,
        96,
        255,
        129,
        22,
        129,
        20,
        97,
        7,
        159,
        87,
        96,
        0,
        128,
        253,
        91,
        150,
        153,
        149,
        152,
        80,
        147,
        150,
        146,
        149,
        148,
        96,
        160,
        132,
        1,
        53,
        148,
        80,
        96,
        192,
        144,
        147,
        1,
        53,
        146,
        145,
        80,
        80,
        86,
        91,
        96,
        0,
        128,
        96,
        64,
        131,
        133,
        3,
        18,
        21,
        97,
        7,
        207,
        87,
        96,
        0,
        128,
        253,
        91,
        97,
        7,
        216,
        131,
        97,
        6,
        172,
        86,
        91,
        145,
        80,
        97,
        7,
        230,
        96,
        32,
        132,
        1,
        97,
        6,
        172,
        86,
        91,
        144,
        80,
        146,
        80,
        146,
        144,
        80,
        86,
        91,
        99,
        78,
        72,
        123,
        113,
        96,
        224,
        27,
        96,
        0,
        82,
        96,
        17,
        96,
        4,
        82,
        96,
        36,
        96,
        0,
        253,
        91,
        96,
        0,
        96,
        1,
        130,
        1,
        97,
        8,
        23,
        87,
        97,
        8,
        23,
        97,
        7,
        239,
        86,
        91,
        80,
        96,
        1,
        1,
        144,
        86,
        91,
        129,
        129,
        3,
        129,
        129,
        17,
        21,
        97,
        2,
        117,
        87,
        97,
        2,
        117,
        97,
        7,
        239,
        86,
        91,
        128,
        130,
        1,
        128,
        130,
        17,
        21,
        97,
        2,
        117,
        87,
        97,
        2,
        117,
        97,
        7,
        239,
        86,
        254,
        162,
        100,
        105,
        112,
        102,
        115,
        88,
        34,
        18,
        32,
        151,
        115,
        79,
        115,
        74,
        250,
        113,
        210,
        219,
        251,
        162,
        224,
        51,
        132,
        251,
        178,
        116,
        206,
        235,
        179,
        120,
        154,
        217,
        87,
        208,
        91,
        86,
        215,
        147,
        86,
        69,
        211,
        100,
        115,
        111,
        108,
        99,
        67,
        0,
        8,
        17,
        0,
        51,
    ];
    ///The bytecode of the contract.
    lazy_static::lazy_static! {
            pub static ref ORIONPOOLV2ERC20_BYTECODE: ::ethers::core::types::Bytes = ::ethers::core::types::Bytes::from(
            __BYTECODE.to_vec(),
        );
    }
    pub struct OrionPoolV2ERC20<M>(::ethers::contract::Contract<M>);
    impl<M> Clone for OrionPoolV2ERC20<M> {
        fn clone(&self) -> Self {
            OrionPoolV2ERC20(self.0.clone())
        }
    }
    impl<M> std::ops::Deref for OrionPoolV2ERC20<M> {
        type Target = ::ethers::contract::Contract<M>;
        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }
    impl<M> std::fmt::Debug for OrionPoolV2ERC20<M> {
        fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            f.debug_tuple(stringify!(OrionPoolV2ERC20))
                .field(&self.address())
                .finish()
        }
    }
    impl<M: ::ethers::providers::Middleware> OrionPoolV2ERC20<M> {
        /// Creates a new contract instance with the specified `ethers`
        /// client at the given `Address`. The contract derefs to a `ethers::Contract`
        /// object
        pub fn new<T: Into<::ethers::core::types::Address>>(
            address: T,
            client: ::std::sync::Arc<M>,
        ) -> Self {
            Self(::ethers::contract::Contract::new(
                address.into(),
                ORIONPOOLV2ERC20_ABI.clone(),
                client,
            ))
        }
        /// Constructs the general purpose `Deployer` instance based on the provided constructor arguments and sends it.
        /// Returns a new instance of a deployer that returns an instance of this contract after sending the transaction
        ///
        /// Notes:
        /// 1. If there are no constructor arguments, you should pass `()` as the argument.
        /// 1. The default poll duration is 7 seconds.
        /// 1. The default number of confirmations is 1 block.
        ///
        ///
        /// # Example
        ///
        /// Generate contract bindings with `abigen!` and deploy a new contract instance.
        ///
        /// *Note*: this requires a `bytecode` and `abi` object in the `greeter.json` artifact.
        ///
        /// ```ignore
        /// # async fn deploy<M: ethers::providers::Middleware>(client: ::std::sync::Arc<M>) {
        ///     abigen!(Greeter,"../greeter.json");
        ///
        ///    let greeter_contract = Greeter::deploy(client, "Hello world!".to_string()).unwrap().send().await.unwrap();
        ///    let msg = greeter_contract.greet().call().await.unwrap();
        /// # }
        /// ```
        pub fn deploy<T: ::ethers::core::abi::Tokenize>(
            client: ::std::sync::Arc<M>,
            constructor_args: T,
        ) -> ::std::result::Result<
            ::ethers::contract::builders::ContractDeployer<M, Self>,
            ::ethers::contract::ContractError<M>,
        > {
            let factory = ::ethers::contract::ContractFactory::new(
                ORIONPOOLV2ERC20_ABI.clone(),
                ORIONPOOLV2ERC20_BYTECODE.clone().into(),
                client,
            );
            let deployer = factory.deploy(constructor_args)?;
            let deployer = ::ethers::contract::ContractDeployer::new(deployer);
            Ok(deployer)
        }
        ///Calls the contract's `DOMAIN_SEPARATOR` (0x3644e515) function
        pub fn domain_separator(&self) -> ::ethers::contract::builders::ContractCall<M, [u8; 32]> {
            self.0
                .method_hash([54, 68, 229, 21], ())
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `PERMIT_TYPEHASH` (0x30adf81f) function
        pub fn permit_typehash(&self) -> ::ethers::contract::builders::ContractCall<M, [u8; 32]> {
            self.0
                .method_hash([48, 173, 248, 31], ())
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `allowance` (0xdd62ed3e) function
        pub fn allowance(
            &self,
            p0: ::ethers::core::types::Address,
            p1: ::ethers::core::types::Address,
        ) -> ::ethers::contract::builders::ContractCall<M, ::ethers::core::types::U256> {
            self.0
                .method_hash([221, 98, 237, 62], (p0, p1))
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `approve` (0x095ea7b3) function
        pub fn approve(
            &self,
            spender: ::ethers::core::types::Address,
            value: ::ethers::core::types::U256,
        ) -> ::ethers::contract::builders::ContractCall<M, bool> {
            self.0
                .method_hash([9, 94, 167, 179], (spender, value))
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `balanceOf` (0x70a08231) function
        pub fn balance_of(
            &self,
            p0: ::ethers::core::types::Address,
        ) -> ::ethers::contract::builders::ContractCall<M, ::ethers::core::types::U256> {
            self.0
                .method_hash([112, 160, 130, 49], p0)
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `decimals` (0x313ce567) function
        pub fn decimals(&self) -> ::ethers::contract::builders::ContractCall<M, u8> {
            self.0
                .method_hash([49, 60, 229, 103], ())
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `name` (0x06fdde03) function
        pub fn name(&self) -> ::ethers::contract::builders::ContractCall<M, String> {
            self.0
                .method_hash([6, 253, 222, 3], ())
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `nonces` (0x7ecebe00) function
        pub fn nonces(
            &self,
            p0: ::ethers::core::types::Address,
        ) -> ::ethers::contract::builders::ContractCall<M, ::ethers::core::types::U256> {
            self.0
                .method_hash([126, 206, 190, 0], p0)
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `permit` (0xd505accf) function
        pub fn permit(
            &self,
            owner: ::ethers::core::types::Address,
            spender: ::ethers::core::types::Address,
            value: ::ethers::core::types::U256,
            deadline: ::ethers::core::types::U256,
            v: u8,
            r: [u8; 32],
            s: [u8; 32],
        ) -> ::ethers::contract::builders::ContractCall<M, ()> {
            self.0
                .method_hash(
                    [213, 5, 172, 207],
                    (owner, spender, value, deadline, v, r, s),
                )
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `symbol` (0x95d89b41) function
        pub fn symbol(&self) -> ::ethers::contract::builders::ContractCall<M, String> {
            self.0
                .method_hash([149, 216, 155, 65], ())
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `totalSupply` (0x18160ddd) function
        pub fn total_supply(
            &self,
        ) -> ::ethers::contract::builders::ContractCall<M, ::ethers::core::types::U256> {
            self.0
                .method_hash([24, 22, 13, 221], ())
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `transfer` (0xa9059cbb) function
        pub fn transfer(
            &self,
            to: ::ethers::core::types::Address,
            value: ::ethers::core::types::U256,
        ) -> ::ethers::contract::builders::ContractCall<M, bool> {
            self.0
                .method_hash([169, 5, 156, 187], (to, value))
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `transferFrom` (0x23b872dd) function
        pub fn transfer_from(
            &self,
            from: ::ethers::core::types::Address,
            to: ::ethers::core::types::Address,
            value: ::ethers::core::types::U256,
        ) -> ::ethers::contract::builders::ContractCall<M, bool> {
            self.0
                .method_hash([35, 184, 114, 221], (from, to, value))
                .expect("method not found (this should never happen)")
        }
        ///Gets the contract's `Approval` event
        pub fn approval_filter(&self) -> ::ethers::contract::builders::Event<M, ApprovalFilter> {
            self.0.event()
        }
        ///Gets the contract's `Transfer` event
        pub fn transfer_filter(&self) -> ::ethers::contract::builders::Event<M, TransferFilter> {
            self.0.event()
        }
        /// Returns an [`Event`](#ethers_contract::builders::Event) builder for all events of this contract
        pub fn events(&self) -> ::ethers::contract::builders::Event<M, OrionPoolV2ERC20Events> {
            self.0.event_with_filter(Default::default())
        }
    }
    impl<M: ::ethers::providers::Middleware> From<::ethers::contract::Contract<M>>
        for OrionPoolV2ERC20<M>
    {
        fn from(contract: ::ethers::contract::Contract<M>) -> Self {
            Self::new(contract.address(), contract.client())
        }
    }
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthEvent,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethevent(name = "Approval", abi = "Approval(address,address,uint256)")]
    pub struct ApprovalFilter {
        #[ethevent(indexed)]
        pub owner: ::ethers::core::types::Address,
        #[ethevent(indexed)]
        pub spender: ::ethers::core::types::Address,
        pub value: ::ethers::core::types::U256,
    }
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthEvent,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethevent(name = "Transfer", abi = "Transfer(address,address,uint256)")]
    pub struct TransferFilter {
        #[ethevent(indexed)]
        pub from: ::ethers::core::types::Address,
        #[ethevent(indexed)]
        pub to: ::ethers::core::types::Address,
        pub value: ::ethers::core::types::U256,
    }
    #[derive(Debug, Clone, PartialEq, Eq, ::ethers::contract::EthAbiType)]
    pub enum OrionPoolV2ERC20Events {
        ApprovalFilter(ApprovalFilter),
        TransferFilter(TransferFilter),
    }
    impl ::ethers::contract::EthLogDecode for OrionPoolV2ERC20Events {
        fn decode_log(
            log: &::ethers::core::abi::RawLog,
        ) -> ::std::result::Result<Self, ::ethers::core::abi::Error>
        where
            Self: Sized,
        {
            if let Ok(decoded) = ApprovalFilter::decode_log(log) {
                return Ok(OrionPoolV2ERC20Events::ApprovalFilter(decoded));
            }
            if let Ok(decoded) = TransferFilter::decode_log(log) {
                return Ok(OrionPoolV2ERC20Events::TransferFilter(decoded));
            }
            Err(::ethers::core::abi::Error::InvalidData)
        }
    }
    impl ::std::fmt::Display for OrionPoolV2ERC20Events {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match self {
                OrionPoolV2ERC20Events::ApprovalFilter(element) => element.fmt(f),
                OrionPoolV2ERC20Events::TransferFilter(element) => element.fmt(f),
            }
        }
    }
    ///Container type for all input parameters for the `DOMAIN_SEPARATOR` function with signature `DOMAIN_SEPARATOR()` and selector `0x3644e515`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "DOMAIN_SEPARATOR", abi = "DOMAIN_SEPARATOR()")]
    pub struct DomainSeparatorCall;
    ///Container type for all input parameters for the `PERMIT_TYPEHASH` function with signature `PERMIT_TYPEHASH()` and selector `0x30adf81f`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "PERMIT_TYPEHASH", abi = "PERMIT_TYPEHASH()")]
    pub struct PermitTypehashCall;
    ///Container type for all input parameters for the `allowance` function with signature `allowance(address,address)` and selector `0xdd62ed3e`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "allowance", abi = "allowance(address,address)")]
    pub struct AllowanceCall(
        pub ::ethers::core::types::Address,
        pub ::ethers::core::types::Address,
    );
    ///Container type for all input parameters for the `approve` function with signature `approve(address,uint256)` and selector `0x095ea7b3`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "approve", abi = "approve(address,uint256)")]
    pub struct ApproveCall {
        pub spender: ::ethers::core::types::Address,
        pub value: ::ethers::core::types::U256,
    }
    ///Container type for all input parameters for the `balanceOf` function with signature `balanceOf(address)` and selector `0x70a08231`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "balanceOf", abi = "balanceOf(address)")]
    pub struct BalanceOfCall(pub ::ethers::core::types::Address);
    ///Container type for all input parameters for the `decimals` function with signature `decimals()` and selector `0x313ce567`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "decimals", abi = "decimals()")]
    pub struct DecimalsCall;
    ///Container type for all input parameters for the `name` function with signature `name()` and selector `0x06fdde03`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "name", abi = "name()")]
    pub struct NameCall;
    ///Container type for all input parameters for the `nonces` function with signature `nonces(address)` and selector `0x7ecebe00`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "nonces", abi = "nonces(address)")]
    pub struct NoncesCall(pub ::ethers::core::types::Address);
    ///Container type for all input parameters for the `permit` function with signature `permit(address,address,uint256,uint256,uint8,bytes32,bytes32)` and selector `0xd505accf`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(
        name = "permit",
        abi = "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"
    )]
    pub struct PermitCall {
        pub owner: ::ethers::core::types::Address,
        pub spender: ::ethers::core::types::Address,
        pub value: ::ethers::core::types::U256,
        pub deadline: ::ethers::core::types::U256,
        pub v: u8,
        pub r: [u8; 32],
        pub s: [u8; 32],
    }
    ///Container type for all input parameters for the `symbol` function with signature `symbol()` and selector `0x95d89b41`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "symbol", abi = "symbol()")]
    pub struct SymbolCall;
    ///Container type for all input parameters for the `totalSupply` function with signature `totalSupply()` and selector `0x18160ddd`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "totalSupply", abi = "totalSupply()")]
    pub struct TotalSupplyCall;
    ///Container type for all input parameters for the `transfer` function with signature `transfer(address,uint256)` and selector `0xa9059cbb`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "transfer", abi = "transfer(address,uint256)")]
    pub struct TransferCall {
        pub to: ::ethers::core::types::Address,
        pub value: ::ethers::core::types::U256,
    }
    ///Container type for all input parameters for the `transferFrom` function with signature `transferFrom(address,address,uint256)` and selector `0x23b872dd`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
    )]
    #[ethcall(name = "transferFrom", abi = "transferFrom(address,address,uint256)")]
    pub struct TransferFromCall {
        pub from: ::ethers::core::types::Address,
        pub to: ::ethers::core::types::Address,
        pub value: ::ethers::core::types::U256,
    }
    #[derive(Debug, Clone, PartialEq, Eq, ::ethers::contract::EthAbiType)]
    pub enum OrionPoolV2ERC20Calls {
        DomainSeparator(DomainSeparatorCall),
        PermitTypehash(PermitTypehashCall),
        Allowance(AllowanceCall),
        Approve(ApproveCall),
        BalanceOf(BalanceOfCall),
        Decimals(DecimalsCall),
        Name(NameCall),
        Nonces(NoncesCall),
        Permit(PermitCall),
        Symbol(SymbolCall),
        TotalSupply(TotalSupplyCall),
        Transfer(TransferCall),
        TransferFrom(TransferFromCall),
    }
    impl ::ethers::core::abi::AbiDecode for OrionPoolV2ERC20Calls {
        fn decode(
            data: impl AsRef<[u8]>,
        ) -> ::std::result::Result<Self, ::ethers::core::abi::AbiError> {
            if let Ok(decoded) =
                <DomainSeparatorCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::DomainSeparator(decoded));
            }
            if let Ok(decoded) =
                <PermitTypehashCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::PermitTypehash(decoded));
            }
            if let Ok(decoded) =
                <AllowanceCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::Allowance(decoded));
            }
            if let Ok(decoded) =
                <ApproveCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::Approve(decoded));
            }
            if let Ok(decoded) =
                <BalanceOfCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::BalanceOf(decoded));
            }
            if let Ok(decoded) =
                <DecimalsCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::Decimals(decoded));
            }
            if let Ok(decoded) = <NameCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::Name(decoded));
            }
            if let Ok(decoded) =
                <NoncesCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::Nonces(decoded));
            }
            if let Ok(decoded) =
                <PermitCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::Permit(decoded));
            }
            if let Ok(decoded) =
                <SymbolCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::Symbol(decoded));
            }
            if let Ok(decoded) =
                <TotalSupplyCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::TotalSupply(decoded));
            }
            if let Ok(decoded) =
                <TransferCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::Transfer(decoded));
            }
            if let Ok(decoded) =
                <TransferFromCall as ::ethers::core::abi::AbiDecode>::decode(data.as_ref())
            {
                return Ok(OrionPoolV2ERC20Calls::TransferFrom(decoded));
            }
            Err(::ethers::core::abi::Error::InvalidData.into())
        }
    }
    impl ::ethers::core::abi::AbiEncode for OrionPoolV2ERC20Calls {
        fn encode(self) -> Vec<u8> {
            match self {
                OrionPoolV2ERC20Calls::DomainSeparator(element) => element.encode(),
                OrionPoolV2ERC20Calls::PermitTypehash(element) => element.encode(),
                OrionPoolV2ERC20Calls::Allowance(element) => element.encode(),
                OrionPoolV2ERC20Calls::Approve(element) => element.encode(),
                OrionPoolV2ERC20Calls::BalanceOf(element) => element.encode(),
                OrionPoolV2ERC20Calls::Decimals(element) => element.encode(),
                OrionPoolV2ERC20Calls::Name(element) => element.encode(),
                OrionPoolV2ERC20Calls::Nonces(element) => element.encode(),
                OrionPoolV2ERC20Calls::Permit(element) => element.encode(),
                OrionPoolV2ERC20Calls::Symbol(element) => element.encode(),
                OrionPoolV2ERC20Calls::TotalSupply(element) => element.encode(),
                OrionPoolV2ERC20Calls::Transfer(element) => element.encode(),
                OrionPoolV2ERC20Calls::TransferFrom(element) => element.encode(),
            }
        }
    }
    impl ::std::fmt::Display for OrionPoolV2ERC20Calls {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match self {
                OrionPoolV2ERC20Calls::DomainSeparator(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::PermitTypehash(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::Allowance(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::Approve(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::BalanceOf(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::Decimals(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::Name(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::Nonces(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::Permit(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::Symbol(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::TotalSupply(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::Transfer(element) => element.fmt(f),
                OrionPoolV2ERC20Calls::TransferFrom(element) => element.fmt(f),
            }
        }
    }
    impl ::std::convert::From<DomainSeparatorCall> for OrionPoolV2ERC20Calls {
        fn from(var: DomainSeparatorCall) -> Self {
            OrionPoolV2ERC20Calls::DomainSeparator(var)
        }
    }
    impl ::std::convert::From<PermitTypehashCall> for OrionPoolV2ERC20Calls {
        fn from(var: PermitTypehashCall) -> Self {
            OrionPoolV2ERC20Calls::PermitTypehash(var)
        }
    }
    impl ::std::convert::From<AllowanceCall> for OrionPoolV2ERC20Calls {
        fn from(var: AllowanceCall) -> Self {
            OrionPoolV2ERC20Calls::Allowance(var)
        }
    }
    impl ::std::convert::From<ApproveCall> for OrionPoolV2ERC20Calls {
        fn from(var: ApproveCall) -> Self {
            OrionPoolV2ERC20Calls::Approve(var)
        }
    }
    impl ::std::convert::From<BalanceOfCall> for OrionPoolV2ERC20Calls {
        fn from(var: BalanceOfCall) -> Self {
            OrionPoolV2ERC20Calls::BalanceOf(var)
        }
    }
    impl ::std::convert::From<DecimalsCall> for OrionPoolV2ERC20Calls {
        fn from(var: DecimalsCall) -> Self {
            OrionPoolV2ERC20Calls::Decimals(var)
        }
    }
    impl ::std::convert::From<NameCall> for OrionPoolV2ERC20Calls {
        fn from(var: NameCall) -> Self {
            OrionPoolV2ERC20Calls::Name(var)
        }
    }
    impl ::std::convert::From<NoncesCall> for OrionPoolV2ERC20Calls {
        fn from(var: NoncesCall) -> Self {
            OrionPoolV2ERC20Calls::Nonces(var)
        }
    }
    impl ::std::convert::From<PermitCall> for OrionPoolV2ERC20Calls {
        fn from(var: PermitCall) -> Self {
            OrionPoolV2ERC20Calls::Permit(var)
        }
    }
    impl ::std::convert::From<SymbolCall> for OrionPoolV2ERC20Calls {
        fn from(var: SymbolCall) -> Self {
            OrionPoolV2ERC20Calls::Symbol(var)
        }
    }
    impl ::std::convert::From<TotalSupplyCall> for OrionPoolV2ERC20Calls {
        fn from(var: TotalSupplyCall) -> Self {
            OrionPoolV2ERC20Calls::TotalSupply(var)
        }
    }
    impl ::std::convert::From<TransferCall> for OrionPoolV2ERC20Calls {
        fn from(var: TransferCall) -> Self {
            OrionPoolV2ERC20Calls::Transfer(var)
        }
    }
    impl ::std::convert::From<TransferFromCall> for OrionPoolV2ERC20Calls {
        fn from(var: TransferFromCall) -> Self {
            OrionPoolV2ERC20Calls::TransferFrom(var)
        }
    }
    ///Container type for all return fields from the `DOMAIN_SEPARATOR` function with signature `DOMAIN_SEPARATOR()` and selector `0x3644e515`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct DomainSeparatorReturn(pub [u8; 32]);
    ///Container type for all return fields from the `PERMIT_TYPEHASH` function with signature `PERMIT_TYPEHASH()` and selector `0x30adf81f`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct PermitTypehashReturn(pub [u8; 32]);
    ///Container type for all return fields from the `allowance` function with signature `allowance(address,address)` and selector `0xdd62ed3e`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct AllowanceReturn(pub ::ethers::core::types::U256);
    ///Container type for all return fields from the `approve` function with signature `approve(address,uint256)` and selector `0x095ea7b3`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct ApproveReturn(pub bool);
    ///Container type for all return fields from the `balanceOf` function with signature `balanceOf(address)` and selector `0x70a08231`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct BalanceOfReturn(pub ::ethers::core::types::U256);
    ///Container type for all return fields from the `decimals` function with signature `decimals()` and selector `0x313ce567`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct DecimalsReturn(pub u8);
    ///Container type for all return fields from the `name` function with signature `name()` and selector `0x06fdde03`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct NameReturn(pub String);
    ///Container type for all return fields from the `nonces` function with signature `nonces(address)` and selector `0x7ecebe00`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct NoncesReturn(pub ::ethers::core::types::U256);
    ///Container type for all return fields from the `symbol` function with signature `symbol()` and selector `0x95d89b41`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct SymbolReturn(pub String);
    ///Container type for all return fields from the `totalSupply` function with signature `totalSupply()` and selector `0x18160ddd`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct TotalSupplyReturn(pub ::ethers::core::types::U256);
    ///Container type for all return fields from the `transfer` function with signature `transfer(address,uint256)` and selector `0xa9059cbb`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct TransferReturn(pub bool);
    ///Container type for all return fields from the `transferFrom` function with signature `transferFrom(address,address,uint256)` and selector `0x23b872dd`
    #[derive(
        Clone,
        Debug,
        Eq,
        PartialEq,
        ::ethers::contract::EthAbiType,
        ::ethers::contract::EthAbiCodec,
        Default,
    )]
    pub struct TransferFromReturn(pub bool);
}
